services:
  cockroach:
    image: cockroachdb/cockroach:v23.1.4
    command: start-single-node --insecure
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    networks:
      - bookstore_network
    ports:
      - "26257:26257"  # SQL
      - "8080:8080"    # Admin UI

  bookstore-server:
    image: bookstore-backend:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DB_USER=root
      - DB_HOST=cockroach
      - DB_NAME=bookstore
      - DB_PORT=26257
      - JWT_SECRET=supersecret
      - PORT=3000
    depends_on:
      - cockroach
    ports:
      - "3000:3000"
    networks:
      - bookstore_network

  bookstore-client:
    image: bookstore-frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://bookstore-server:3000/api
    ports:
      - "5173:80"
    depends_on:
      - bookstore-server
    networks:
      - bookstore_network

volumes:
  cockroach-data:

networks:
  bookstore_network:
    driver: bridge
